# Generated by Django 3.2.7 on 2021-11-18 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_auto_20211118_1149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notesconfig',
            name='message_id',
            field=models.CharField(help_text='帖子id', max_length=20, verbose_name='帖子id'),
        ),
    ]
