# Generated by Django 3.2.7 on 2021-11-18 04:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0003_alter_notesconfig_message_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notesconfig',
            name='user',
        ),
    ]
