# Generated by Django 3.2.7 on 2021-11-18 02:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='goods',
            old_name='is_home',
            new_name='is_hot',
        ),
    ]
