# Generated by Django 3.2.7 on 2021-11-18 03:33

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0002_rename_is_home_goods_is_hot'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='goods',
            options={'verbose_name': '商品', 'verbose_name_plural': '商品'},
        ),
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('setting_id', models.CharField(max_length=20, verbose_name='配置id')),
                ('name', models.CharField(max_length=20, verbose_name='配置名称')),
                ('info', models.CharField(max_length=100, verbose_name='配置信息')),
                ('add_time', models.DateField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='是否删除')),
                ('goods', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='goods.goods', verbose_name='商品')),
            ],
            options={
                'verbose_name': '参数设置',
                'verbose_name_plural': '参数设置',
            },
        ),
    ]
