# Generated by Django 3.2.7 on 2021-11-25 01:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0002_alter_orderinfo_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shoppingcart',
            name='goods_num',
        ),
        migrations.AddField(
            model_name='shoppingcart',
            name='nums',
            field=models.IntegerField(default=0, verbose_name='商品数量'),
        ),
        migrations.AlterField(
            model_name='shoppingcart',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间'),
        ),
    ]
