# Generated by Django 3.2.7 on 2021-11-25 01:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0003_auto_20211125_0902'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shoppingcart',
            old_name='nums',
            new_name='goods_num',
        ),
    ]
