# Generated by Django 3.2.7 on 2021-12-05 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0007_shoppingcart_is_choosen'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderinfo',
            name='buy_only',
            field=models.BooleanField(default=False, verbose_name='是否单独购买'),
        ),
    ]
