# Generated by Django 3.2.7 on 2021-12-06 03:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0008_orderinfo_buy_only'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderinfo',
            name='add_time',
        ),
    ]
