# Generated by Django 3.2.7 on 2021-12-08 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0009_remove_orderinfo_add_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordergoods',
            name='add_time',
        ),
    ]
