# Generated by Django 3.2.7 on 2021-11-18 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='name',
            field=models.CharField(max_length=30, verbose_name='姓名'),
        ),
    ]
