# Generated by Django 3.2.7 on 2021-11-26 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_userprofile_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='verifycode',
            name='mobile',
        ),
        migrations.AddField(
            model_name='verifycode',
            name='email',
            field=models.CharField(default=' ', max_length=30, verbose_name='邮箱'),
        ),
    ]
