# Generated by Django 3.2.7 on 2021-11-29 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20211129_1031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verifycode',
            name='email',
            field=models.CharField(max_length=30, verbose_name='邮箱'),
        ),
    ]
