# Generated by Django 3.2.7 on 2021-11-29 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_verifycode_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='email',
            field=models.CharField(default=' ', max_length=50, verbose_name='邮箱'),
        ),
    ]
