# Generated by Django 3.2.7 on 2021-11-30 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_userprofile_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='name',
            field=models.CharField(default=' ', max_length=30, verbose_name='姓名'),
        ),
    ]
