# Generated by Django 3.2.7 on 2021-12-01 11:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_userprofile_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verifycode',
            name='add_time',
            field=models.DateField(default=datetime.datetime(2021, 12, 1, 19, 30, 9, 540599), verbose_name='添加时间'),
        ),
    ]
