# Generated by Django 3.2.7 on 2021-12-02 08:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_alter_verifycode_add_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verifycode',
            name='add_time',
            field=models.DateField(default=datetime.datetime(2021, 12, 2, 16, 41, 1, 623432), verbose_name='添加时间'),
        ),
    ]
